//Generated by CodeGen
//Generated Time: 2018-04-14 14:05:39
using System;
using System.Collections.Generic;
using System.Text;

namespace HCW.Model
{
    [Serializable]
    public class tbl_news_classInfo 
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>不允许Null</remark>
        public int cid
        {
            get;set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nchar</returns>
        /// <remark>允许Null</remark>
        public string name
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nchar</returns>
        /// <remark>允许Null</remark>
        public string ename
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? pid
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? rid
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? depth
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? czid
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>tinyint</returns>
        /// <remark>允许Null</remark>
        public byte? everqi
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string keywords
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string description
        {
            get;
            set;
        }

    }
}
