//Generated by CodeGen
//Generated Time: 2018-04-14 17:05:38
using System;
using System.Collections.Generic;
using System.Text;

namespace HCW.Model
{
    [Serializable]
    public class tbl_3dInfo : CPKJModel
    {

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>不允许Null</remark>
        public int id
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? qi
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? a
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? b
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? c
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string zj1
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string zj2
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string zj3
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>smalldatetime</returns>
        /// <remark>允许Null</remark>
        public DateTime? date
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>datetime</returns>
        /// <remark>允许Null</remark>
        public DateTime? addtime
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string sjh
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string sjx
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string tzmoney
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? hz
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string kjh
        {
            get;
            set;
        }

        /// <summary>
        /// 开机号
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string kjih
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? kjh_zu
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? kjh_jo
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? kjh_dx
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? kjh_zh
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? kjh_hz_dx
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? kjh_hz_jo
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? sjh_zu
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? sjh_jo
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? sjh_dx
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? sjh_zh
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? sjh_hz
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? sjh_hz_dx
        {
            get;
            set;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? sjh_hz_jo
        {
            get;
            set;
        }
    }
}
