//Generated by CodeGen
//Generated Time: 2018-04-15 18:04:37
using System;
using System.Collections.Generic;
using System.Text;

namespace HCW.Model
{
    [Serializable]
    public class tbl_p3Info : CPKJModel
    {
        public bool IsidPassed = false;
        public bool IsqiPassed = false;
        public bool IsaPassed = false;
        public bool IsbPassed = false;
        public bool IscPassed = false;
        public bool IsdPassed = false;
        public bool IsePassed = false;
        public bool Iszj1Passed = false;
        public bool Iszj2Passed = false;
        public bool Iszj3Passed = false;
        public bool Iszjp5Passed = false;
        public bool IsdatePassed = false;
        public bool IsaddtimePassed = false;
        public bool IstzmoneyPassed = false;
        public bool Istzmoneyp5Passed = false;
        public bool IshzPassed = false;
        public bool IskjhPassed = false;
        public bool IssjhPassed = false;
        public bool IssjhtypePassed = false;

        private int mid;
        private int? mqi;
        private int? ma;
        private int? mb;
        private int? mc;
        private int? md;
        private int? me;
        private int? mzj1;
        private int? mzj2;
        private int? mzj3;
        private int? mzjp5;
        private DateTime? mdate;
        private DateTime? maddtime;
        private string mtzmoney = "";
        private string mtzmoneyp5 = "";
        private int? mhz;
        private string mkjh = "";
        private string msjh = "";
        private string msjhtype = "";


        public tbl_p3Info() { }

        public tbl_p3Info(int mid, 
            int? mqi, 
            int? ma, 
            int? mb, 
            int? mc, 
            int? md, 
            int? me, 
            int? mzj1, 
            int? mzj2, 
            int? mzj3, 
            int? mzjp5, 
            DateTime? mdate, 
            DateTime? maddtime, 
            string mtzmoney, 
            string mtzmoneyp5, 
            int? mhz, 
            string mkjh, 
            string msjh, 
            string msjhtype)
        {
            this.mid = mid;
            this.mqi = mqi;
            this.ma = ma;
            this.mb = mb;
            this.mc = mc;
            this.md = md;
            this.me = me;
            this.mzj1 = mzj1;
            this.mzj2 = mzj2;
            this.mzj3 = mzj3;
            this.mzjp5 = mzjp5;
            this.mdate = mdate;
            this.maddtime = maddtime;
            this.mtzmoney = mtzmoney;
            this.mtzmoneyp5 = mtzmoneyp5;
            this.mhz = mhz;
            this.mkjh = mkjh;
            this.msjh = msjh;
            this.msjhtype = msjhtype;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>不允许Null</remark>
        public int id
        {
            get { return mid; }
            set
            {
                mid = value;
                IsidPassed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? qi
        {
            get { return mqi; }
            set
            {
                mqi = value;
                IsqiPassed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? a
        {
            get { return ma; }
            set
            {
                ma = value;
                IsaPassed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? b
        {
            get { return mb; }
            set
            {
                mb = value;
                IsbPassed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? c
        {
            get { return mc; }
            set
            {
                mc = value;
                IscPassed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? d
        {
            get { return md; }
            set
            {
                md = value;
                IsdPassed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? e
        {
            get { return me; }
            set
            {
                me = value;
                IsePassed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? zj1
        {
            get { return mzj1; }
            set
            {
                mzj1 = value;
                Iszj1Passed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? zj2
        {
            get { return mzj2; }
            set
            {
                mzj2 = value;
                Iszj2Passed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? zj3
        {
            get { return mzj3; }
            set
            {
                mzj3 = value;
                Iszj3Passed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? zjp5
        {
            get { return mzjp5; }
            set
            {
                mzjp5 = value;
                Iszjp5Passed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>datetime</returns>
        /// <remark>允许Null</remark>
        public DateTime? date
        {
            get { return mdate; }
            set
            {
                mdate = value;
                IsdatePassed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>datetime</returns>
        /// <remark>允许Null</remark>
        public DateTime? addtime
        {
            get { return maddtime; }
            set
            {
                maddtime = value;
                IsaddtimePassed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string tzmoney
        {
            get { return mtzmoney; }
            set
            {
                mtzmoney = value;
                IstzmoneyPassed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string tzmoneyp5
        {
            get { return mtzmoneyp5; }
            set
            {
                mtzmoneyp5 = value;
                Istzmoneyp5Passed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>int</returns>
        /// <remark>允许Null</remark>
        public int? hz
        {
            get { return mhz; }
            set
            {
                mhz = value;
                IshzPassed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string kjh
        {
            get { return mkjh; }
            set
            {
                mkjh = value;
                IskjhPassed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string sjh
        {
            get { return msjh; }
            set
            {
                msjh = value;
                IssjhPassed = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns>nvarchar</returns>
        /// <remark>允许Null</remark>
        public string sjhtype
        {
            get { return msjhtype; }
            set
            {
                msjhtype = value;
                IssjhtypePassed = true;
            }
        }

        public tbl_p3Info Clonetbl_p3()
        {
            return (tbl_p3Info)this.MemberwiseClone();
        }

        public object Clone()
        {
            return this.MemberwiseClone();
        }
    }
}
